### ISSUE TITLE
Update DG with design details - Austin

### ISSUE THREAD

**Issue by CelestineTan03** [AY2324S1-CS2103T-W08-1/tp#91]
- Each member should describe the implementation of at least one enhancement he/she has added (or planning to add).
- Expected length: 1+ page per person
- The description can contain things such as,
   - How the feature is implemented (or is going to be implemented).
   - Why it is implemented that way.
   - Alternatives considered.

**Comment by AustinHuang1203** [comment]
Will write for help and confirmation/clear command
